/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Classes;



/**
 *
 * @author ponsa
 */
public class Interfaz extends javax.swing.JFrame {
    

    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    
    public void updateQueues(Planta planta1, Planta planta2){
        updatePriority1Planta1(planta1);
//        updatePriority2(planta1);
//        updatePriority3(planta1);
//        updateReinforce(planta1);
//        updatePriority1(planta2);
//        updatePriority2(planta2);
//        updatePriority3(planta2);
//        updateReinforce(planta2);
    }
    
    public void updatePriority1Planta1(Planta planta){
        
        Queue cola = planta.getPriority1();
        QNode current = cola.getHead();
        
        
        for (int i = 0; i < planta.getPriority1().getSize(); i++) {
            switch(i){
                case 0:
                    Queue1Plant1Position7.setText("<html>" + current.getPhone().getID() + "<br>"+ current.getPhone().getModel() + "</html>");
                    break;
                    
                 case 1:
                    Queue1Plant1Position6.setText("<html>" + current.getPhone().getID() + "<br>"+ current.getPhone().getModel() + "</html>");
                    break;
                    
                    case 2:
                    Queue1Plant1Position5.setText("<html>" + current.getPhone().getID() + "<br>"+ current.getPhone().getModel() + "</html>");
                    break;
                    
                    case 3:
                    Queue1Plant1Position4.setText("<html>" + current.getPhone().getID() + "<br>"+ current.getPhone().getModel() + "</html>");
                    break;
                    
                    case 4:
                    Queue1Plant1Position3.setText("<html>" + current.getPhone().getID() + "<br>"+ current.getPhone().getModel() + "</html>");
                    break;
                    
                    case 5:
                    Queue1Plant1Position2.setText("<html>" + current.getPhone().getID() + "<br>"+ current.getPhone().getModel() + "</html>");
                    break;
                    
                    case 6:
                   Queue1Plant1Position1.setText("<html>" + current.getPhone().getID() + "<br>"+ current.getPhone().getModel() + "</html>");
                    break;
                    
                    case 7:
                    Queue1Plant1Position0.setText("<html>" + current.getPhone().getID() + "<br>"+ current.getPhone().getModel() + "</html>");
                    break;
            }
            current = current.getNext();
        }
        
        
    }
    
//    public void setAIStatus(String status){
//        Level1QueuePlant1.setText(status);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Queue1Plant1 = new javax.swing.JPanel();
        Queue1Plant1Position0 = new javax.swing.JLabel();
        Queue1Plant1Position1 = new javax.swing.JLabel();
        Queue1Plant1Position2 = new javax.swing.JLabel();
        Queue1Plant1Position3 = new javax.swing.JLabel();
        Queue1Plant1Position4 = new javax.swing.JLabel();
        Queue1Plant1Position5 = new javax.swing.JLabel();
        Queue1Plant1Position6 = new javax.swing.JLabel();
        Queue1Plant1Position7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Queue1Plant1.setBackground(new java.awt.Color(255, 255, 255));
        Queue1Plant1.setBorder(new javax.swing.border.MatteBorder(null));

        Queue1Plant1Position0.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Queue1Plant1Position1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Queue1Plant1Position2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Queue1Plant1Position3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Queue1Plant1Position4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Queue1Plant1Position5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Queue1Plant1Position6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Queue1Plant1Position7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout Queue1Plant1Layout = new javax.swing.GroupLayout(Queue1Plant1);
        Queue1Plant1.setLayout(Queue1Plant1Layout);
        Queue1Plant1Layout.setHorizontalGroup(
            Queue1Plant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Queue1Plant1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Queue1Plant1Position0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Queue1Plant1Position1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Queue1Plant1Position2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Queue1Plant1Position3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Queue1Plant1Position4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Queue1Plant1Position5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Queue1Plant1Position6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Queue1Plant1Position7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        Queue1Plant1Layout.setVerticalGroup(
            Queue1Plant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Queue1Plant1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Queue1Plant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Queue1Plant1Layout.createSequentialGroup()
                        .addGroup(Queue1Plant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Queue1Plant1Position0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(Queue1Plant1Position1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Queue1Plant1Layout.createSequentialGroup()
                        .addGroup(Queue1Plant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Queue1Plant1Position2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Queue1Plant1Position3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Queue1Plant1Position4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Queue1Plant1Position5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Queue1Plant1Position7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Queue1Plant1Position6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanel1.add(Queue1Plant1);
        Queue1Plant1.setBounds(10, 300, 560, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/Images/portada_sono-bisque-doll-31.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1210, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Queue1Plant1;
    private javax.swing.JLabel Queue1Plant1Position0;
    private javax.swing.JLabel Queue1Plant1Position1;
    private javax.swing.JLabel Queue1Plant1Position2;
    private javax.swing.JLabel Queue1Plant1Position3;
    private javax.swing.JLabel Queue1Plant1Position4;
    private javax.swing.JLabel Queue1Plant1Position5;
    private javax.swing.JLabel Queue1Plant1Position6;
    private javax.swing.JLabel Queue1Plant1Position7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}


