/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Classes;



/**
 *
 * @author ponsa
 */
public class Interfaz extends javax.swing.JFrame {
    

    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    
    public void updateQueues(Planta planta1, Planta planta2){
        updatePlanta1(planta1);
        updatePlanta2(planta2);
    }
    
    public void setResult(String battleResult){
        result.setText(battleResult);
    }
    
    public void setSkynetStatus(String status){
        skynetStatus.setText(status);
    }
    
    public void setPhone1(String phone){
        phone1.setText(phone);
    }
    
    public void setPhone2(String phone){
        phone2.setText(phone);
    }
    
    public void updatePlanta1(Planta planta){
        
        String queue1 = "";
        String queue2 = "";
        String queue3 = "";
        String reinforce = "";
        
        Queue cola1 = planta.getPriority1();
        Queue cola2 = planta.getPriority2();
        Queue cola3 = planta.getPriority3();
        Queue colaRefuerzo = planta.getReinforcement();
        
        QNode current1 = cola1.getHead();
        QNode current2 = cola2.getHead();
        QNode current3 = cola3.getHead();
        QNode currentR = colaRefuerzo.getHead();
        
        while (current1 != null){
            queue1 += "  " + current1.getPhone().getModel() + " " + current1.getPhone().getID() + "\n";
            current1 = current1.getNext();
        }
        
        while (current2 != null){
            queue2 += "  " + current2.getPhone().getModel() + " " + current2.getPhone().getID() + "\n";
            current2 = current2.getNext();
        }
        
        while (current3 != null){
            queue3 += "  " + current3.getPhone().getModel() + " " + current3.getPhone().getID() + "\n";
            current3 = current3.getNext();
        }
        
        while (currentR != null){
            reinforce += "  " + currentR.getPhone().getModel() + " " + currentR.getPhone().getID() + "\n";
            currentR = currentR.getNext();
        }
        
        Q1P1Text.setText(queue1);
        Q2P1Text.setText(queue2);
        Q3P1Text.setText(queue3);
        RP1Text.setText(reinforce);
        
    }
    
    public void updatePlanta2(Planta planta){
        
        String queue1 = "";
        String queue2 = "";
        String queue3 = "";
        String reinforce = "";
        
        Queue cola1 = planta.getPriority1();
        Queue cola2 = planta.getPriority2();
        Queue cola3 = planta.getPriority3();
        Queue colaRefuerzo = planta.getReinforcement();
        
        QNode current1 = cola1.getHead();
        QNode current2 = cola2.getHead();
        QNode current3 = cola3.getHead();
        QNode currentR = colaRefuerzo.getHead();
        
        while (current1 != null){
            queue1 += "  " + current1.getPhone().getModel() + " " + current1.getPhone().getID() + "\n";
            current1 = current1.getNext();
        }
        
        while (current2 != null){
            queue2 += "  " + current2.getPhone().getModel() + " " + current2.getPhone().getID() + "\n";
            current2 = current2.getNext();
        }
        
        while (current3 != null){
            queue3 += "  " + current3.getPhone().getModel() + " " + current3.getPhone().getID() + "\n";
            current3 = current3.getNext();
        }
        
        while (currentR != null){
            reinforce += "  " + currentR.getPhone().getModel() + " " + currentR.getPhone().getID() + "\n";
            currentR = currentR.getNext();
        }
        
        Q1P2Text.setText(queue1);
        Q2P2Text.setText(queue2);
        Q3P2Text.setText(queue3);
        RP2Text.setText(reinforce);
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Plant2Title = new javax.swing.JPanel();
        Plant2 = new javax.swing.JLabel();
        Plant1Title = new javax.swing.JPanel();
        Plant1 = new javax.swing.JLabel();
        SKYNET = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SkynetStatus = new javax.swing.JPanel();
        skynetStatus = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        result = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        nivel1Text = new javax.swing.JLabel();
        phone1Name = new javax.swing.JPanel();
        phone1 = new javax.swing.JLabel();
        vs = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        phone2Name = new javax.swing.JPanel();
        phone2 = new javax.swing.JLabel();
        Q1P1 = new javax.swing.JScrollPane();
        Q1P1Text = new javax.swing.JTextArea();
        Q2P1 = new javax.swing.JScrollPane();
        Q2P1Text = new javax.swing.JTextArea();
        Q3P1 = new javax.swing.JScrollPane();
        Q3P1Text = new javax.swing.JTextArea();
        RP1 = new javax.swing.JScrollPane();
        RP1Text = new javax.swing.JTextArea();
        Q1P2 = new javax.swing.JScrollPane();
        Q1P2Text = new javax.swing.JTextArea();
        Q2P2 = new javax.swing.JScrollPane();
        Q2P2Text = new javax.swing.JTextArea();
        Q3P2 = new javax.swing.JScrollPane();
        Q3P2Text = new javax.swing.JTextArea();
        RP2 = new javax.swing.JScrollPane();
        RP2Text = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Plant2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Plant2.setText("PLANTA 2");

        javax.swing.GroupLayout Plant2TitleLayout = new javax.swing.GroupLayout(Plant2Title);
        Plant2Title.setLayout(Plant2TitleLayout);
        Plant2TitleLayout.setHorizontalGroup(
            Plant2TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plant2TitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Plant2)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Plant2TitleLayout.setVerticalGroup(
            Plant2TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Plant2TitleLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(Plant2)
                .addContainerGap())
        );

        jPanel1.add(Plant2Title);
        Plant2Title.setBounds(900, 20, 100, 30);

        Plant1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Plant1.setText("PLANTA 1");

        javax.swing.GroupLayout Plant1TitleLayout = new javax.swing.GroupLayout(Plant1Title);
        Plant1Title.setLayout(Plant1TitleLayout);
        Plant1TitleLayout.setHorizontalGroup(
            Plant1TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plant1TitleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Plant1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Plant1TitleLayout.setVerticalGroup(
            Plant1TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Plant1TitleLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(Plant1)
                .addContainerGap())
        );

        jPanel1.add(Plant1Title);
        Plant1Title.setBounds(240, 20, 100, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SKYNET");

        javax.swing.GroupLayout SKYNETLayout = new javax.swing.GroupLayout(SKYNET);
        SKYNET.setLayout(SKYNETLayout);
        SKYNETLayout.setHorizontalGroup(
            SKYNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SKYNETLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );
        SKYNETLayout.setVerticalGroup(
            SKYNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SKYNETLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(SKYNET);
        SKYNET.setBounds(560, 10, 100, 30);

        skynetStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout SkynetStatusLayout = new javax.swing.GroupLayout(SkynetStatus);
        SkynetStatus.setLayout(SkynetStatusLayout);
        SkynetStatusLayout.setHorizontalGroup(
            SkynetStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkynetStatusLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(skynetStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        SkynetStatusLayout.setVerticalGroup(
            SkynetStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkynetStatusLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(skynetStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(SkynetStatus);
        SkynetStatus.setBounds(560, 40, 100, 50);

        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(resultPanel);
        resultPanel.setBounds(550, 150, 120, 60);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nivel 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 110, 50, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nivel 3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(160, 110, 50, 30);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Refuerzo");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(40, 110, 60, 30);

        nivel1Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivel1Text.setText("Nivel 1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nivel1Text)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nivel1Text)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(400, 110, 50, 30);

        phone1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout phone1NameLayout = new javax.swing.GroupLayout(phone1Name);
        phone1Name.setLayout(phone1NameLayout);
        phone1NameLayout.setHorizontalGroup(
            phone1NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phone1NameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phone1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        phone1NameLayout.setVerticalGroup(
            phone1NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phone1NameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phone1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(phone1Name);
        phone1Name.setBounds(460, 100, 120, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("vs");

        javax.swing.GroupLayout vsLayout = new javax.swing.GroupLayout(vs);
        vs.setLayout(vsLayout);
        vsLayout.setHorizontalGroup(
            vsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        vsLayout.setVerticalGroup(
            vsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(vs);
        vs.setBounds(580, 100, 50, 30);

        phone2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout phone2NameLayout = new javax.swing.GroupLayout(phone2Name);
        phone2Name.setLayout(phone2NameLayout);
        phone2NameLayout.setHorizontalGroup(
            phone2NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phone2NameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phone2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        phone2NameLayout.setVerticalGroup(
            phone2NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phone2NameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phone2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(phone2Name);
        phone2Name.setBounds(630, 100, 120, 30);

        Q1P1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Q1P1Text.setColumns(20);
        Q1P1Text.setRows(5);
        Q1P1.setViewportView(Q1P1Text);

        jPanel1.add(Q1P1);
        Q1P1.setBounds(370, 150, 110, 390);

        Q2P1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Q2P1Text.setColumns(20);
        Q2P1Text.setRows(5);
        Q2P1.setViewportView(Q2P1Text);

        jPanel1.add(Q2P1);
        Q2P1.setBounds(250, 150, 110, 390);

        Q3P1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Q3P1Text.setColumns(20);
        Q3P1Text.setRows(5);
        Q3P1.setViewportView(Q3P1Text);

        jPanel1.add(Q3P1);
        Q3P1.setBounds(130, 150, 110, 390);

        RP1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        RP1Text.setColumns(20);
        RP1Text.setRows(5);
        RP1.setViewportView(RP1Text);

        jPanel1.add(RP1);
        RP1.setBounds(10, 150, 110, 390);

        Q1P2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Q1P2Text.setColumns(20);
        Q1P2Text.setRows(5);
        Q1P2.setViewportView(Q1P2Text);

        jPanel1.add(Q1P2);
        Q1P2.setBounds(730, 150, 110, 390);

        Q2P2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Q2P2Text.setColumns(20);
        Q2P2Text.setRows(5);
        Q2P2.setViewportView(Q2P2Text);

        jPanel1.add(Q2P2);
        Q2P2.setBounds(850, 150, 110, 390);

        Q3P2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Q3P2Text.setColumns(20);
        Q3P2Text.setRows(5);
        Q3P2.setViewportView(Q3P2Text);

        jPanel1.add(Q3P2);
        Q3P2.setBounds(1090, 150, 110, 390);

        RP2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        RP2Text.setColumns(20);
        RP2Text.setRows(5);
        RP2.setViewportView(RP2Text);

        jPanel1.add(RP2);
        RP2.setBounds(970, 150, 110, 390);

        jLabel2.setText("Nivel 1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(760, 110, 50, 30);

        jLabel7.setText("Nivel 2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(880, 110, 50, 30);

        jLabel8.setText("Nivel 3");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(1000, 110, 50, 30);

        jLabel9.setText("Refuerzo");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(1110, 110, 58, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/Images/portada_sono-bisque-doll-31.jpg"))); // NOI18N
        fondo.setText("jLabel2");
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 1210, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Plant1;
    private javax.swing.JPanel Plant1Title;
    private javax.swing.JLabel Plant2;
    private javax.swing.JPanel Plant2Title;
    private javax.swing.JScrollPane Q1P1;
    private javax.swing.JTextArea Q1P1Text;
    private javax.swing.JScrollPane Q1P2;
    private javax.swing.JTextArea Q1P2Text;
    private javax.swing.JScrollPane Q2P1;
    private javax.swing.JTextArea Q2P1Text;
    private javax.swing.JScrollPane Q2P2;
    private javax.swing.JTextArea Q2P2Text;
    private javax.swing.JScrollPane Q3P1;
    private javax.swing.JTextArea Q3P1Text;
    private javax.swing.JScrollPane Q3P2;
    private javax.swing.JTextArea Q3P2Text;
    private javax.swing.JScrollPane RP1;
    private javax.swing.JTextArea RP1Text;
    private javax.swing.JScrollPane RP2;
    private javax.swing.JTextArea RP2Text;
    private javax.swing.JPanel SKYNET;
    private javax.swing.JPanel SkynetStatus;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel nivel1Text;
    private javax.swing.JLabel phone1;
    private javax.swing.JPanel phone1Name;
    private javax.swing.JLabel phone2;
    private javax.swing.JPanel phone2Name;
    private javax.swing.JLabel result;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel skynetStatus;
    private javax.swing.JPanel vs;
    // End of variables declaration//GEN-END:variables


}


